In [12]:
import numpy as np

x, vx, y, vy = 5, 20, 0.8, 10

B = np.array([[x / np.sqrt(x**x+y**2), y / np.sqrt(x**x+y**2)],
              [-y / (x**x+y**2), x / (x**x+y**2), ], 
              [y*(vx*y-vy*x)/np.power((x**x+y**2), 1.5), x*(vy*x-x*y)/np.power((x**x+y**2), 1.5)]])
print(B)

A = np.array([[1.88, 0.32],[0.32, 2.25]])

C = B.dot(A).dot(B.T)
print(C)
A2 = np.linalg.pinv(B).dot(C).dot(np.linalg.pinv(B.T))
# print(np.linalg.pinv(B))
print(A2)

[[ 0.08943356  0.01430937]
 [-0.00025595  0.00159967]
 [-0.00015565  0.00131619]]
[[1.63166583e-02 5.30780365e-05 5.31603596e-05]
 [5.30780365e-05 5.61876200e-06 4.62474157e-06]
 [5.31603596e-05 4.62474157e-06 3.81224763e-06]]
[[1.88 0.32]
 [0.32 2.25]]
